CREATE DATABASE recursosHumanos;

USE recursosHumanos;

CREATE TABLE colaboradores (
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR (40),
SOBRENOME VARCHAR(40),
CARGO VARCHAR(50),
SALARIO FLOAT);

INSERT INTO colaboradores (NOME, SOBRENOME, CARGO, SALARIO) VALUES 
('DEMESTRIA', 'DEVONE LOVATO','CANTORA', 15000.00),
('ROBERTO CARLOS', 'BRAGA','CANTOR', 8500.00),
('JOHN FRANCIS', 'BONGIOVI JR.','CANTOR', 1200.24),
('MADONNA LOUISE', 'VERONICA CICCONE','CANTORA', 18000.14),
('BILLIE JOE', 'ARMSTRONG','CANTOR', 1500.12);

SELECT * FROM colaboradores WHERE SALARIO > 2000;

SELECT * FROM colaboradores WHERE SALARIO < 2000;

UPDATE colaboradores SET SALARIO=15275.25 WHERE ID=1;


 